greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"

quarkus:
  http:
    port: 8081
  hibernate-orm:
    database:
      database:
        generation: "drop-and-create"
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/book
      driver: org.postgresql.Driver
  otel:
    traces:
      include-static-resources: true

# With Profiles
"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:book
        driver: org.h2.Driver
